version: '3.4'


networks:
  inner_net:
    driver: bridge
  outer_net:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    networks:
     - inner_net

  rabbitmq:
    image: rabbitmq:3-management-alpine   
    depends_on:     
     - sqlserver
    networks:
     - inner_net

  company.identityserver:
    image: ${DOCKER_REGISTRY-}companyidentityserver
    build:
      context: .
      dockerfile: Company.IdentityServer/Dockerfile   
    networks:
      - inner_net
      - outer_net

  bank.payments.api:
    image: ${DOCKER_REGISTRY-}bankpaymentsapi
    build:
      context: .
      dockerfile: Bank.Payments.Api/Dockerfile    
    networks:
      - inner_net

  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: PaymentGateway.Api/Dockerfile    
    links:
      - "sqlserver:mysqlserver"
    depends_on:     
      - sqlserver
      - rabbitmq    
      - company.identityserver
    networks:
      - inner_net
      - outer_net

  paymentgateway.processor.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayprocessorapi
    build:
      context: .
      dockerfile: PaymentGateway.Processor.Api/Dockerfile   
    links:
      - "sqlserver:mysqlserver"
    depends_on:     
      - sqlserver
      - rabbitmq      
      - company.identityserver
    networks:
      - inner_net
      - outer_net

  client.payments.api:
    image: ${DOCKER_REGISTRY-}clientpaymentsapi
    build:
      context: .
      dockerfile: Client.Payments.Api/Dockerfile   
    depends_on:     
      - paymentgateway.api
      - paymentgateway.processor.api
      - company.identityserver
    networks:
      - outer_net

  prometheus:
    image: prom/prometheus
    links:
      - paymentgateway.api:paymentgateway.api
      - paymentgateway.processor.api:paymentgateway.processor.api
    depends_on:
      - paymentgateway.api
      - paymentgateway.processor.api
    networks:
      - inner_net
      - outer_net #added to gather metrics from the client

#  grafana:
#  image : grafana/grafana
#    depends_on: 
#      - prometheus  
#    networks:
#      - inner_net