version: '3.4'

services:
  sqlserver:
    environment:
      - SA_PASSWORD=CataCl1sma!
      - ACCEPT_EULA=Y
    ports:
      - "11433:1433"   
    volumes:  
      - ./data/mssql:/var/opt/mssql3 
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672" 
  paymentgateway.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventBrokerConnection=rabbitmq
      - EventBrokerUserName=guest
      - EventBrokerPassword=guest
      - Authority=https://company.identityserver/
      - ConnectionStrings__SqlConnection=Server=mysqlserver;Database=PaymentGateway.Api;User Id=sa;Password=CataCl1sma!
    ports:
      - "6000:80"
      - "6001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  paymentgateway.processor.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - EventBrokerConnection=rabbitmq
      - EventBrokerUserName=guest
      - EventBrokerPassword=guest
      - BankPaymentsAddress=http://bank.payments.api/
      - Authority=https://company.identityserver/
      - ConnectionStrings__SqlConnection=Server=mysqlserver;Database=PaymentGateway.Processor.Api;User Id=sa;Password=CataCl1sma!
    ports:
      - "7000:80"
      - "7001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  bank.payments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  client.payments.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - PaymentGatewayAddress=http://paymentgateway.api/
      - PaymentGatewayProcessorAddress=http://paymentgateway.processor.api/
      - MerchantId=53D92C77-3C0E-447C-ABC5-0AF6CF829A22
      - ClientId=amazonId
      - ClientSecret=amazonSecret
      - IdentityServer=https://company.identityserver/
    ports:
      - "8000:80"
      - "8001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  company.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "9000:80"
      - "9001:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

