version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
      
  bank.payments.api:
    image: ${DOCKER_REGISTRY-}bankpaymentsapi
    build:
      context: .
      dockerfile: Bank.Payments.Api/Dockerfile

  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: PaymentGateway.Api/Dockerfile
    depends_on:     
      - rabbitmq


  paymentgateway.processor.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayprocessorapi
    build:
      context: .
      dockerfile: PaymentGateway.Processor.Api/Dockerfile
    depends_on:     
      - rabbitmq
      




