version: '3.4'

services:
  bank.payments.api:
    image: ${DOCKER_REGISTRY-}bankpaymentsapi
    build:
      context: .
      dockerfile: Bank.Payments.Api/Dockerfile

  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: PaymentGateway.Api/Dockerfile

