version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
      
  paymentgateway.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayapi
    build:
      context: .
      dockerfile: PaymentGateway.Api/Dockerfile
    depends_on:     
      - rabbitmq


  paymentgateway.processor.api:
    image: ${DOCKER_REGISTRY-}paymentgatewayprocessorapi
    build:
      context: .
      dockerfile: PaymentGateway.Processor.Api/Dockerfile
    depends_on:     
      - rabbitmq
      

