# my global config
global:
  scrape_interval:     60s 
  evaluation_interval: 60s 

  external_labels:
      monitor: 'paymentgateway'


scrape_configs:

  - job_name: 'prometheus'   
    scrape_interval: 30s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'paymentgateway.api'   
    static_configs:
    - targets:  ['paymentgateway.api']
      labels:
          alias: "paymentgateway.api"

  - job_name: 'paymentgateway.processor.api'  
    scrape_interval: 30s     
    static_configs:
    - targets: ['paymentgateway.processor.api']
      labels:
          alias: "paymentgateway.processor.api"

  - job_name: 'client.payments.api'   
    scrape_interval: 30s  
    static_configs:
    - targets:  ['client.payments.api']
      labels:
          alias: "client.payments.api"

  - job_name: 'company.identityserver'   
    static_configs:
    - targets:  ['company.identityserver']
      labels:
          alias: "company.identityserver"