# my global config
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

  external_labels:
      monitor: 'paymentgateway'


scrape_configs:

  - job_name: 'prometheus'   
    scrape_interval: 10s
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'paymentgateway.api'   
    scrape_interval: 10s  
    static_configs:
    - targets:  ['paymentgateway.api']
      labels:
          alias: "paymentgateway.api"

  - job_name: 'paymentgateway.processor.api'  
    scrape_interval: 10s     
    #scheme: https
    static_configs:
    - targets: ['paymentgateway.processor.api']
      labels:
          alias: "paymentgateway.processor.api"
       # - paymentgateway.processor
